### ISSUE TITLE
Azurelib-forge-1.19.2-1.0.30 crashes on startup

### ISSUE THREAD

**Issue by Minebrah** [AzureDoom/AzureLib#14]
https://gist.github.com/Minebrah/41e93509c966286e059238cdcee9c82e

**Comment by AzureDoom** [comment]
This is an issue with one of your mods that use, if you can provide an export of this modpack, I can look for it and it to the excluded name list!

**Comment by Fazzoc** [comment]
am having the same issue, i can gladly send in the mods (though that's tested on fabric)

Log: https://mclo.gs/8B9R3Kn

All the mods used: https://drive.google.com/file/d/1O2rEpu19CZz_o_aBclX6oot_wuFCpmf8/view?usp=sharing

**Comment by AzureDoom** [comment]
> 

Thank you! Will test in the next few days.

**Comment by Minebrah** [comment]
Damn, I wish I knew how. To be honest this is just a personal modpack I'm making that I run on the Minecraft launcher via forge. I have no idea how to export it. But my modlist is in the crash report so maybe between me and Fazzoc's mod list you'll be able to narrow it down? Crossing my fingers, I've always used your mods in the past and I don't want to go without.

**Comment by Fazzoc** [comment]
What i done is just compress the mods folder of mine in to a zip, and put them to google drive due to GitHub file size limits

**Comment by AzureDoom** [comment]
@Fazzoc yours was another issue completely and is now fixed in the next update here. 

@Minebrah sadly that's a shit ton of mods so I would need an export or if you can disable Geckolib and see what mods are requiring it and send that, I can test that way.

**Comment by Minebrah** [comment]
You're right, it is ALOT of mods. So maybe I'll try doing what you said and removing Geckolib to see if that can narrow it down and make it a little easier.

[02Sep2023 20:23:01.348] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'geckolib3', Requested by: 'omni_card', Expected range: '[3.1.40,3.2)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'creeperoverhaul', Expected range: '[3.1.8,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'goodall', Expected range: '[3.0.12,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'graveyard', Expected range: '[3.1.34,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'duckling', Expected range: '[3.1.0,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'naturalist', Expected range: '[3.1.9,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'whatareyouvotingfor', Expected range: '[3.1.14,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'silverbirch', Expected range: '[0,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'sprout', Expected range: '[3.0.12,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'davespotioneering', Expected range: '[1.16.5-3.1.34,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'staywarmtogether', Expected range: '[3.1.36,)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'mutantmore', Expected range: '[3.1.39,4.0.0)', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'siegemachines', Expected range: '[3.00,]', Actual version: '[MISSING]'
	Mod ID: 'geckolib3', Requested by: 'irons_spellbooks', Expected range: '[3.1.39,)', Actual version: '[MISSING]'

I'm using the latest versions of each mod:

omni_card-1.19.2-1.3.0
creeperoverhaul-2.0.9-forge
goodall-1.2.0-forge
The_Graveyard_2.5.3_(FORGE)_for_1.19.2.
duckling-2.0.8-forge
naturalist-forge-3.0.4-1.19.2
whatareyouvotingfor2022-1.19.2-1.9
silver_birch-1.19.2-v1.1.0.0
sprout-1.4.4-forge
davespotioneering-1.19.2-1.2.1
staywarmtogether-19.2.0.4
mutantmore-1.19.2-early-access-1.0.7
[1.19.2]-Medieval-Siege-Machines-v1.10
irons_spellbooks-1.19.2-1.2.1

Hope this helps, if not we can try something else, like the export.

**Comment by AzureDoom** [comment]
![image](https://github.com/AzureDoom/AzureLib/assets/7415711/b29f8165-b876-4958-9dd8-a4392289587d)

Just tested all of those mods and it's launching just fine for me.

**Comment by Minebrah** [comment]
Ok I'm going to try to figure out which mod is causing this on my own and I'll let you know what I come up with. Thanks for trying anyway I appreciate it I know its a lot of mods to check.
