### ISSUE TITLE
Can't stack Spawn Egg from Gigeresque Mod

### ISSUE THREAD

**Issue by WorldSpinAround** [AzureDoom/AzureLib#2]
All other Spawn Eggs from the base Game can be stacked, it is especially obvious when you middle-click an egg in creative to get a full stack of it.
Since spawn eggs can not be obtainable in survival, there isn't an obvious reason why it wouldn't be stackable like other spawn eggs.

I was told to move this here.

**Comment by AzureDoom** [comment]
Pushed an update to fix this!
