### ISSUE TITLE
Crash with mek tools

### ISSUE THREAD

**Issue by GrizzBear01** [AzureDoom/AzureLib#27]
ATLauncher
forge 47.2.1 - 1.20.1
mekanism (all but additions) 10.4.2.16

game crash rendering entity in world, always with mek glowarmor (appologies if not your mod causing issue), not enough crashes suggests its due to azurelib

no crash occurs with azurelib 1.0.32 but higher versions cause crash

[crash-2023-10-31_12.56.44-client.txt](https://github.com/AzureDoom/AzureLib/files/13216748/crash-2023-10-31_12.56.44-client.txt)

**Comment by AzureDoom** [comment]
Fixed now! Thanks for the info!
