### ISSUE TITLE
GlowArmor cannot be cast to class 

### ISSUE THREAD

**Issue by codec-d** [AzureDoom/AzureLib#33]
pretty serious bug as it prevents users from rentering their world once bug is encountered.

It looks like the issue comes from a mixin in the AzureLib mod trying to cast a class from Mekanism Tools to a Minecraft class in the HumanoidArmorLayer.

> The game crashed whilst rendering entity in world
> Error: java.lang.ClassCastException: class mekanism.tools.client.render.GlowArmor cannot be cast to class net.minecraft.client.model.HumanoidModel (mekanism.tools.client.render.GlowArmor is in module mekanismtools@10.4.5 of loader 'TRANSFORMER' @7d5ef1c3; net.minecraft.client.model.HumanoidModel is in module minecraft@1.20.1 of loader 'TRANSFORMER' @7d5ef1c3)

https://pastebin.com/YPXSU8c2

Suspected Mod: 
	AzureLib (azurelib)
Mixin class: 
	mod.azure.azurelib.mixins.NeoMixinHumanoidArmorLayer
Target:  
	net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer
	
java.lang.ClassCastException: 
	class mekanism.tools.client.render.GlowArmor cannot be cast to  
	class net.minecraft.client.model.HumanoidModel

**Comment by AzureDoom** [comment]
God fucking damn, my fix had reverted at some point. God damn it git. 

I'll have a fix out here in a few hours.

**Comment by codec-d** [comment]
thank god. I thought I was going crazy because you had definitely fixed it. ty ily
