### ISSUE TITLE
Crash after updating Azurelib

### ISSUE THREAD

**Issue by Darkmega18** [AzureDoom/AzureLib#35]
I was hit by this crash while loading the game after updating azurelib. I'm not sure what it implies, but it doesn't get very far.

[crash-2023-12-05_03.49.45-fml.txt](https://github.com/AzureDoom/AzureLib/files/13549422/crash-2023-12-05_03.49.45-fml.txt)

**Comment by Standard-Issue-Username** [comment]
I'm getting the same error.

@Darkmega18 Roll back Azurelib to 2.0.12 until another version releases.

**Comment by Darkmega18** [comment]
thats what I did do. A friend said it's likely neo and normie forge diverging too much at this point if I had to guess. since I'm still on a fairly old 1.20.1 forge version out of necessity for a mod that my pack runs.

**Comment by Standard-Issue-Username** [comment]
Well, that seems likely since I'm in the same boat there. I'm keeping an eye on the new loaders but not doing anything until a few key mods make the switch.

**Comment by AzureDoom** [comment]
> thats what I did do. A friend said it's likely neo and normie forge diverging too much at this point if I had to guess. since I'm still on a fairly old 1.20.1 forge version out of necessity for a mod that my pack runs.

Nah, the issue is a base Forge. It has an issue with me trying to register things conditionally. Will have an update here today to just registry my keybind always.

**Comment by Darkmega18** [comment]
oh neat. noice. thanks.
