### ISSUE TITLE
Incendiary Attachment

### ISSUE THREAD

**Issue by OHKOBunny** [AzureDoom/AzureLib#39]
If this gets added to loot you find it on all kinds of gear, despite JEI insisting it can't go on anything. A log probably isn't necessary since this is probably an accident, but I don't think a Library mod needs an enchantment like this.

It is worth mentioning that I am using the forge version, 1.20.1, and both Epic Knights and KnightsnMages. Most updated versions available each

**Comment by AzureDoom** [comment]
It's an attachment for my gun mods that use this, so yes it's intended to be included

**Comment by AzureDoom** [comment]
If using any forge version above 47.1.3 however, no support will be given as I only support neoforge and fabric when it comes to 1.20.1+

**Comment by OHKOBunny** [comment]
Ohhh that makes sense, and yeah I'm using 1.20.1
