### ISSUE TITLE
on forge 1.20.1 47.2.19 eldritch end is crashing due to azure lib 

### ISSUE THREAD

**Issue by jojofenin99** [AzureDoom/AzureLib#40]
here are the logs and crash logs:
[latest.log](https://github.com/AzureDoom/AzureLib/files/14389517/latest.log)
[crash-2024-02-23_13.35.10-client.txt](https://github.com/AzureDoom/AzureLib/files/14389523/crash-2024-02-23_13.35.10-client.txt)

**Comment by AzureDoom** [comment]
I don't support any forge version past 47.1.3, as I only do neoforge for 1.20.1 and above, which targets 47.1.3 for its patches
