### ISSUE TITLE
Error coming up for a few mods

### ISSUE THREAD

**Issue by DrThraxGLA** [AzureDoom/AzureLib#41]
Sophisticated Backpacks getting error from AzureLib same with guardvillagers, Create: dieselgenerators, Create: Interiors, Farmer's Delight idk about sophisticatedstorage and I want to play epicsamurai mod with what I got here Error code txt
[crash-2024-02-24_18.09.09-client.txt](https://github.com/AzureDoom/AzureLib/files/14394841/crash-2024-02-24_18.09.09-client.txt)

**Comment by AzureDoom** [comment]
This is due to Optifine, which is not supported. Please use https://www.curseforge.com/minecraft/mc-mods/embeddium and https://www.curseforge.com/minecraft/mc-mods/oculus instead.
