### ISSUE TITLE
Adding the lib to mods

### ISSUE THREAD

**Issue by PaulOlague** [AzureDoom/AzureLib#44]
When I'm adding the lib to my mods (alone or with others) theres an error that is shown. I dont use The Aether and if i added, the game still shows this problem.

The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: The Aether (aether) encountered an error during the common_setup event phase

![imagen_2024-03-03_014525172](https://github.com/AzureDoom/AzureLib/assets/103787099/42cc909b-937f-4736-8dcf-ccda70ea3a86)

**Comment by AzureDoom** [comment]
Need a proper log

**Comment by AzureDoom** [comment]
No proper log provided
