### ISSUE TITLE
[main/WARN] [mixin/] 1,20,1 Forge 47.2.7

### ISSUE THREAD

**Issue by Krimatoria** [AzureDoom/AzureLib#45]
is azure doom part of azurelib?
I have
- nyfsspiders
- gigeresque-connector-1.20.1-0.5.62.jar

Perhaps this is gigeresque , which loads something through the Fabric API
![image](https://github.com/AzureDoom/AzureLib/assets/106809386/2c2bfcb2-3a00-4f4b-bd8b-0af5197f2b93)

I just started Googling the names in the log and saw a link to your wiki where just Alines) apparently there are no errors here, right? Are these just some kind of warnings?

> [00:54:53] [main/WARN] [mixin/]: Method overwrite conflict for onLookAt in nyfsspiders.mixins.json:LivingEntityMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.common.LivingEntityMixin. Skipping method.
> [00:54:53] [main/WARN] [mixin/]: Method overwrite conflict for onNotifyDataManagerChange in nyfsspiders.mixins.json:LivingEntityMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.common.LivingEntityMixin. Skipping method.
> [00:54:53] [main/WARN] [mixin/]: Method overwrite conflict for onTravel in nyfsspiders.mixins.json:LivingEntityMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.common.LivingEntityMixin. Skipping method.
> [00:54:53] [main/WARN] [mixin/]: Method overwrite conflict for onJump in nyfsspiders.mixins.json:LivingEntityMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.common.LivingEntityMixin. Skipping method.
> [00:54:53] [main/WARN] [mixin/]: Method overwrite conflict for getTargetYaw in nyfsspiders.mixins.json:LivingEntityClientMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.client.LivingEntityClientMixin. Skipping method.
> [00:54:53] [main/WARN] [mixin/]: Method overwrite conflict for getTargetPitch in nyfsspiders.mixins.json:LivingEntityClientMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.client.LivingEntityClientMixin. Skipping method.
> [00:54:53] [main/WARN] [mixin/]: Method overwrite conflict for getTargetHeadYaw in nyfsspiders.mixins.json:LivingEntityClientMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.client.LivingEntityClientMixin. Skipping method.
[00:54:56] [pool-4-thread-1/WARN] [mixin/]: Method overwrite conflict for onLivingTick in nyfsspiders.mixins.json:MobEntityMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.common.MobEntityMixin. Skipping method.
[00:54:56] [pool-4-thread-1/WARN] [mixin/]: Method overwrite conflict for onTick in nyfsspiders.mixins.json:MobEntityMixin from mod nyfsspiders, previously written by mod.azuredoom.bettercrawling.mixin.common.MobEntityMixin. Skipping method.

**Comment by AzureDoom** [comment]
Not the right mid
