### ISSUE TITLE
goblin traders incompatible (?)

### ISSUE THREAD

**Issue by existentialclown** [AzureDoom/AzureLib#54]
playing on a modded forge server. the server itself has no issue running the two mods together, but when i try to even start forge minecraft (for myself) it crashes. 
[goblinazurecrash.txt](https://github.com/user-attachments/files/15844342/goblinazurecrash.txt)

**Comment by AzureDoom** [comment]
If you are using Optifine, that's why

**Comment by existentialclown** [comment]
ive seen people with shaders use this mod also, is it just that optifine is incompatible with the library?

**Comment by AzureDoom** [comment]
It's just optifine, the better shader ones work just fine. No one should be using Optifine honestly
