### ISSUE TITLE
Possible incompatibility with VULKAN MOD

### ISSUE THREAD

**Issue by JaguarRognar** [AzureDoom/AzureLib#55]
It's just my hunch, you guys are the experts. Crashreport:
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-06-15 22:52:23
Description: Rendering item

java.lang.NullPointerException: Cannot invoke "net.vulkanmod.vulkan.texture.VulkanImage.updateTextureSampler(boolean, boolean, boolean)" because "this.vulkanImage" is null
	at net.minecraft.class_1044.method_4527(class_1044.java:1065)
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243)
	at net.minecraft.class_4668.method_23516(class_4668.java:37)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1079)
	at net.minecraft.class_4668.method_23516(class_4668.java:37)
	at net.minecraft.class_1921.method_23012(class_1921.java:864)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:97)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:80)
	at net.minecraft.class_332.method_51452(class_332.java:128)
	at net.minecraft.class_332.method_51425(class_332.java:532)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at net.minecraft.class_465.method_2385(class_465.java:249)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1044.method_4527(class_1044.java:1065)
	at net.minecraft.class_4668$class_4683.method_23563(class_4668.java:243)
	at net.minecraft.class_4668.method_23516(class_4668.java:37)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
	at net.minecraft.class_1921$class_4687.method_23595(class_1921.java:1079)
	at net.minecraft.class_4668.method_23516(class_4668.java:37)
	at net.minecraft.class_1921.method_23012(class_1921.java:864)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:97)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:80)
	at net.minecraft.class_332.method_51452(class_332.java:128)
	at net.minecraft.class_332.method_51425(class_332.java:532)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at net.minecraft.class_465.method_2385(class_465.java:249)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)

-- Item being rendered --
Details:
	Item Type: end_crystal
	Item Damage: 0
	Item NBT: null
	Item Foil: true
Stacktrace:
	at net.minecraft.class_332.method_51425(class_332.java:532)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at net.minecraft.class_465.method_2385(class_465.java:249)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (300, 85). Absolute: (600.000000, 170.000000)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['JoseDortum'/85, l='ClientLevel', x=10.76, y=-60.00, z=-75.72]]
	Chunk stats: 729, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 3511 game time, 3511 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: fabric, vanilla, file/TZP_1.20.1_2.7.zip, file/FreshAnimations_v1.9.zip, file/3D Default 1.20 v1.10.0.zip, file/Scary Spider 1.20+.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.11, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 369904752 bytes (352 MiB) / 1207959552 bytes (1152 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce MX130
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x174d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4665
	Graphics card #1 name: Intel(R) UHD Graphics 620
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x5917
	Graphics card #1 versionInfo: DriverVersion=25.20.100.6444
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17795.60
	Virtual memory used (MB): 11311.66
	Swap memory total (MB): 9728.00
	Swap memory used (MB): 837.16
	JVM Flags: 9 total; -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+IgnoreUnrecognizedVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		amecs: Amecs 1.3.10+mc.1.20.1
		animated_guns: Simple Animated Guns 1.3
		another_furniture: Another Furniture 1.20.1-3.0.1
		architectury: Architectury 9.2.14
		azurelib: AzureLib 2.0.25
		bagofholding: Bag Of Holding 8.0.2
			extensibleenums: Extensible Enums 7.0.1
			puzzlesapi: Puzzles Api 8.1.6
				puzzlesaccessapi: Puzzles Access Api 8.0.9
		brewinandchewin: Brewin And Chewin 3.0.3+1.20.1
			mm: Manningham Mills 2.3
		callablehorsefabric: CallableHorseFabric 1.0.0
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		cave_dweller: Cave Dweller 1.4.0
		charmofundying: Charm of Undying 6.5.0+1.20.1
			spectrelib: SpectreLib 0.13.15+1.20.1
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		companion: Companion 5.1.0
		dehydration: Dehydration 1.3.6
		entity_model_features: Entity Model Features 2.0.2
		entity_texture_features: Entity Texture Features 6.0.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		farmersdelight: Farmer's Delight 1.20.1-2.1.1+refabricated
			porting_lib_accessors: Porting Lib Accessors 2.3.4+1.20.1
			porting_lib_base: Porting Lib Base 2.3.4+1.20.1
				com_electronwill_night-config_core: core 3.6.6
				com_electronwill_night-config_toml: toml 3.6.6
				porting_lib_attributes: Porting Lib Attributes 2.3.4+1.20.1
				porting_lib_common: Porting Lib Common 2.3.4+1.20.1
				porting_lib_core: Porting Lib Core 2.3.4+1.20.1
				porting_lib_entity: Porting Lib Entity 2.3.4+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.4+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.4+1.20.1
				porting_lib_transfer: Porting Lib Transfer 2.3.4+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.4+1.20.1
				reach-entity-attributes: Reach Entity Attributes 2.4.0
			porting_lib_client_events: Porting Lib Client Events 2.3.4+1.20.1
			porting_lib_config: Porting Lib Config 2.3.4+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.4+1.20.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.4+1.20.1
			porting_lib_loot: Porting Lib Loot 2.3.4+1.20.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 2.3.4+1.20.1
			porting_lib_registries: Porting Lib Registries 2.3.4+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.4+1.20.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		fps: FPS Monitor 1.20-1.3.0-Fabric
		geckolib: GeckoLib 4 4.4.4
			com_eliotlash_mclib_mclib: mclib 20
		guardvillagers: GuardVillagers 2.0.9-1.20.1
			midnightlib: MidnightLib 1.4.1
		herobrine: The Legend of Herobrine 0.7.2
		horsebuff: HorseBuff 2.1.2
		horseexpert: Horse Expert 8.1.1
		horseshoes: Horseshoes 1.0.2
		indypets: IndyPets - Independent Pets 1.3.4
		jamlib: JamLib 0.6.1+1.20.x
		java: Java HotSpot(TM) 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.2+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		man: The Man from the Fog 1.1.1
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
		midnightlurker: Midnight Lurker 1.20.1-1.0.2
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.17.0+mc1.20.1
		modmenu: Mod Menu 7.2.2
		mousewheelie: Mouse Wheelie 1.13.0+mc1.20.1
			amecsapi: Amecs API 1.5.1+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		musketmod: Musket Mod 1.4.8
		mutantmonsters: Mutant Monsters 8.0.7
		niftycarts: NiftyCarts 3.0.2+1.20.1
		no-shield-delay: No Shield Delay 1.0.0
		notenoughanimations: NotEnoughAnimations 1.7.3
		owo: oωo 0.11.2+1.20
			blue_endless_jankson: jankson 1.2.2
		puzzleslib: Puzzles Lib 8.1.20
		shouldersurfing: Shoulder Surfing Reloaded 3.2.0
		stackablepotions: Stackable Potions 1.0.0
		trinkets: Trinkets 3.7.2
		utilitybelt: Utility Belt 1.3.6+1.20.1
			tutorial-lib: Tutorial Lib 1.1.2+1.20.x
		variantvanillablocks: Variant Vanilla Blocks 1.3.8
		vulkanmod: VulkanMod 0.4.2
			org_lwjgl_lwjgl-shaderc: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-linux: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-macos: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-macos-arm64: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-windows: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-vma: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-linux: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-macos: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-macos-arm64: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-windows: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vulkan: lwjgl-vulkan 3.3.2
			org_lwjgl_lwjgl-vulkan_natives-macos: lwjgl-vulkan 3.3.2
			org_lwjgl_lwjgl-vulkan_natives-macos-arm64: lwjgl-vulkan 3.3.2
		weaponmaster: YDM's Weapon Master 3.0.5
	Launched Version: fabric-loader-0.15.11-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric, vanilla, file/TZP_1.20.1_2.7.zip, file/FreshAnimations_v1.9.zip, file/3D Default 1.20 v1.10.0.zip, file/Scary Spider 1.20+.zip
	Current Language: es_mx
	CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['JoseDortum'/85, l='ServerLevel[Mundo nuevo]', x=10.76, y=-60.00, z=-75.72]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by AzureDoom** [comment]
Need a smaller test for this, as that's a lot of mods. Need what mod is exactly using AzureLib in your modpack to test against as MCDoom is rendering fine for me with AzureLib and VulkanMod
![2024-06-17_14 10 34](https://github.com/AzureDoom/AzureLib/assets/7415711/bced2deb-2e9b-4baa-84cd-6c3ef0a2af20)

**Comment by JaguarRognar** [comment]
Of course, I was trying to install Simple Animated Guns 1.3, plus I had GeckoLib 4 4.4.4 already installed.

**Comment by AzureDoom** [comment]
This is Vulkan breaking my mixin here: https://github.com/AzureDoom/AzureLib/blob/1.20/common/src/main/java/mod/azure/azurelib/mixins/MixinItemRenderer.java#L22-L28

This is on the Vulkan mods side to fix, not AzureLibs as this mixin works fine with the normal MC renders.

**Comment by JaguarRognar** [comment]
I think I understand, I have some clarity now. Thank you for your kindness.
