### ISSUE TITLE
Strange error that keeps me to connect to a test dedicated server in localhost

### ISSUE THREAD

**Issue by vico93** [AzureDoom/AzureLib#56]
For context, i was investigating a strange error that first appeared to me in singleplayer, everytime i try to create a new world that spawns me in either desert or badland biomes the internal server seems to just "die", leaving only a tiny fraction of the world generated and all entities paralized.

Before trying to mess with my modpack, i decided to boot up a test dedicated server in my computer with the same world type (large biomes) and seed to see if further errors would appear or if i would be able to play normally. But when i tried to connect to the test server it insta kicked me and [this error](https://gist.github.com/vico93/7751e13c2a1c9f2e288cc37c46bfbbdd) appeared in the console, but no crash occurred. Don't know yet if this is related with the original problem i'm getting, but since it mentions azurelib i decided to report anyway to let you aware.

I'm using MC 1.21, fabric-loader-0.15.11-1.21, fabric-api-0.100.3+1.21 and azurelib-fabric-1.21-2.3.2.

**Comment by AzureDoom** [comment]
Thanks for the report! This was actually found to affect 1.20.6 as well, so a patch for both it and 1.21 has been pushed now!
