### ISSUE TITLE
Shaders with advanced materials (reflection, emissive) not working on armor, entities

### ISSUE THREAD

**Issue by blunderbust** [AzureDoom/AzureLib#57]
This is the same issue with Geckolib, but posting here in case it hasnt been seen or mentioned yet.

[https://github.com/bernie-g/geckolib/issues/546](https://github.com/bernie-g/geckolib/issues/546)

removing "client.TextureManagerMixin" from the mixin.json file fixes the issue.

**Comment by AzureDoom** [comment]
> This is the same issue with Geckolib, but posting here in case it hasnt been seen or mentioned yet.
> 
> [bernie-g/geckolib#546](https://github.com/bernie-g/geckolib/issues/546)
> 
> removing "client.TextureManagerMixin" from the mixin.json file fixes the issue.

Do you have a basic pack that I can use for testing this on my end? Something like a CF export will help a ton!

**Comment by AzureDoom** [comment]
![image](https://github.com/AzureDoom/AzureLib/assets/7415711/1a267261-ba0d-4d7a-91ea-f7dd0455c924)
![2024-06-25_19 50 07](https://github.com/AzureDoom/AzureLib/assets/7415711/817e1b1d-f497-44eb-8d5d-97b08fc10e18)
Can't reproduce on my end for this?

**Comment by blunderbust** [comment]
im down to fabri api, iris, sodium.  running bsl shaders with advanced materials. patrix texture pack for iron golem textures.
  if i turn on azure or gecko, golem glowing eyes and advanced texture features break.  here are some screenshots.

![2024-06-26_11 59 11](https://github.com/AzureDoom/AzureLib/assets/36343224/743b054b-9793-481e-abfc-779ecf7b4dc2)
![2024-06-26_12 00 43](https://github.com/AzureDoom/AzureLib/assets/36343224/d3ad7cc4-d339-4c13-a2c1-58b1518982ef)
![Screenshot 2024-06-26 120849](https://github.com/AzureDoom/AzureLib/assets/36343224/a82aa24a-6ce4-420a-95ca-ee1fa4f72ad8)

**Comment by AzureDoom** [comment]
Will be fixed in the next update pending some other fixes.
