### ISSUE TITLE
Crash with just core mods (DARF/Azurelib (Unsure))

### ISSUE THREAD

**Issue by Overkill77** [AzureDoom/AzureLib#6]
First off id like to say that I don't know if I should open this issue on Azurelib or AzureDooms Angel Ring, so ill post it up on both.
---
### **Currently with these mods enabled:**
AzureDooms Angel Ring
Azurelib
FabricApi
Trinkets

### **My assumption:**
The game crashes on boot, I think, after reading the crash log that, the new update (AzureDooms Angel Ring) broke it.
I could be very wrong though, so that's why I'm posting it on both projects.

### **The crash log:**
[crash-2023-05-15_17.55.44-client.txt](https://github.com/AzureDoom/AzureLib/files/11480129/crash-2023-05-15_17.55.44-client.txt)

### **Point of focus:** 

Caused by: java.lang.NullPointerException: Cannot read field "max_ring_durability" because "mod.azure.doomangelring.DoomAngelRing.config" is null
	at mod.azure.doomangelring.AngelRingItem.<init>(AngelRingItem.java:17)
	at mod.azure.doomangelring.DoomAngelRing.<clinit>(DoomAngelRing.java:19)
	... 16 more

**Comment by AzureDoom** [comment]
Tracking via https://github.com/AzureDoom/Doom-Angel-Ring-Fabric/issues/5
