### ISSUE TITLE
Crash on start up. Something to do with "GeoRenderPhaseEventFactory" - what ever that is...

### ISSUE THREAD

**Issue by CopperBoltwire** [AzureDoom/AzureLib#60]
[latest.log](https://github.com/user-attachments/files/16179402/latest.log)
Tried to downgrade to version to 2.0.29 from 2.0.30, both versions throws an error. I'll keep downgrading to try and find one that don't. If it still fails. Then i give up for now.

**Comment by AzureDoom** [comment]
You need to go to 2.0.28 or so, MCDoom won't be updated for some time for this azurelib change as I'm busy with it's 1.21 rewrite.
