### ISSUE TITLE
Azurelib causes datagen to never exit

### ISSUE THREAD

**Issue by solonovamax** [AzureDoom/AzureLib#62]
If azurelib is loaded and you run a datagen, then the jvm will not exit.

The reason it's not exiting is due to the "Auto-Sync thread" thread:
https://github.com/AzureDoom/AzureLib/blob/13867f9b6728dec58a291b7dbdcc91b6b08d1817/common/src/main/java/mod/azure/azurelib/common/internal/common/config/io/FileWatchManager.java#L51-L55

I believe this is because the `SERVER_STOPPED` event is not emitted when exiting from the datagen:
https://github.com/AzureDoom/AzureLib/blob/13867f9b6728dec58a291b7dbdcc91b6b08d1817/fabric/src/main/java/mod/azure/azurelib/fabric/FabricAzureLibMod.java#L32-L34

I will be opening an issue for this on the fabric repo as well.

**Comment by solonovamax** [comment]
Also, ideally, the thread should be started as a daemon thread. this allows the jvm to exit even if the thread has not been properly cleaned up.

**Comment by AzureDoom** [comment]
This seems more like an issue with the Fabrics side of Datagen than with how AzureLib/Configuration handles closing the thread, as NeoForge data generation is not suffering any issues from this. The proper fix for this would have to be on Fabrics side tbh.

**Comment by AzureDoom** [comment]
This is resolved in the latest version now.

**Comment by solonovamax** [comment]
@AzureDoom Hi, can a build for 1.20.1 fabric be pushed to maven? Currently, the `2.0.31` release is not in your maven repo, only the `2.0.30` release.

**Comment by solonovamax** [comment]
Also, the issue is not on fabric's end at all

According to FabricMC/fabric-loom#1145,
> Neither of these [`ServerLifecycleEvents.SERVER_STARTING` and `ServerLifecycleEvents.SERVER_STOPPING`] should be fired during data generation.

the use of `ServerLifecycleEvents.SERVER_STOPPING` is incorrect, as it is not expected to be fired during datagen.
