### ISSUE TITLE
Sources for common elements do not exist in platform jars, and common elements are not remapped.

### ISSUE THREAD

**Issue by solonovamax** [AzureDoom/AzureLib#63]
Grouping these two issues together as they're kinda similar.

1. The `-sources` jar for the platform releases (eg. `-fabric`, `-forge`, etc.) only contain the sources for that platform, and don't contain the sources for the common elements.
2. If you add the common 'platform', then it will not be remapped by fabric-loom. This is because there is no `fabric.mod.json`. The fix I have seen used by other mods for this is to include a dummy `fabric.mod.json` which is never included in the platform jars.

**Comment by AzureDoom** [comment]
As per discord, this is not something not planned to be fixed, as this happens only with Yarn and should be fixed on Looms side, not by providing hacks with dummy jsons.
