### ISSUE TITLE
Crash ONLY when using AzureLib 2.0.27 or below, however, MCDoom doesn't support the newer AzureLib versions. So although this isn't an issue on newer versions, I am unable to use them with MCDoom.

### ISSUE THREAD

**Issue by Mqony** [AzureDoom/AzureLib#64]
[crash-2024-08-13_22.30.14-fml.txt](https://github.com/user-attachments/files/16607955/crash-2024-08-13_22.30.14-fml.txt)

**Comment by 5A93** [comment]
Same problem, thought it was the newest Epic Fight caused it

**Comment by Mqony** [comment]
Was it epic fight or no?

**Comment by AzureDoom** [comment]
This is known and willl be fixed after the 1.21 release however I have no eta due to health reasons.

**Comment by 5A93** [comment]
> Was it epic fight or no?

No
