### ISSUE TITLE
[Log] Mixin config Error - 1.20.1

### ISSUE THREAD

**Issue by velox-resurrected** [AzureDoom/AzureLib#65]
When starting up the game, you will get the following error message in the logs(latest.log).

_"Mixin config azurelib.mixins.json does not specify "minVersion" property"_

and also this message

_"Mixin config azurelib.forge.mixins.json does not specify "minVersion" property"_

**Comment by AzureDoom** [comment]
That's a non issue and doesn't affect anything, can be disregarded
