### ISSUE TITLE
AzureLib causes Minecraft 1.21 to get stuck at the end of the loading screen, causing game to not boot.

### ISSUE THREAD

**Issue by MylesGit** [AzureDoom/AzureLib#68]
AzureLib Armor 2.3.2
Fabric Loader 0.16.5
Minecraft 1.21

This is probably a mod incompatibility of some sort. I will try to look into it further, wondering if anyone has any input.

Logs Below
https://mclo.gs/SKuDyIn

Screenshot Below
![image](https://github.com/user-attachments/assets/d21c8936-a045-4aa2-a694-cd2dd7b1ae88)

**Comment by AzureDoom** [comment]
This is not the correct repo for Azurelib Armor, please open an issue here: https://github.com/AzureDoom/AzureLib-Armor both CF and Modrinth lead there, not here. Please ensure you are are updated as well, nex time, you are 3 versions behind.

**Comment by MylesGit** [comment]
Apologies, I'll create an issue in the correct repo. I followed the repo that the jar / prism provides which must be incorrect.
![image](https://github.com/user-attachments/assets/96c7b357-6383-4706-9283-c8afe1a3bd2a)
 Have a good day.
