### ISSUE TITLE
[BUG] crash with new version of azurelib

### ISSUE THREAD

**Issue by VaporeonScripts** [AzureDoom/AzureLib#73]
***ALL INFO MUST BE FILLED IN OR THE ISSUE WILL BE CLOSED AS INVALID***

**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: neoforge .61
Mod version: .25

**Describe the bug**
crash with new version

**To Reproduce**
install the mod 
**Screenshots**
https://mclo.gs/QcKtBTz

**Comment by AzureDoom** [comment]
Because that version requires .62 of NeoForge as per the commit here: https://github.com/AzureDoom/AzureLib/commit/a55889baae5d1b70988ec05c2d20a2c5aa8e220b

**Comment by VaporeonScripts** [comment]
yeah but eternal starlight doesnt work if i put .62 :sob:

**Comment by AzureDoom** [comment]
Then you'll have to downgrade azurelib in the meantime

**Comment by VaporeonScripts** [comment]
doing that rn, also the owner of that mod just replied,a fix is coming! :D
