### ISSUE TITLE
Mixin config azurelib.mixins.json/azurelib.forge.mixins.json does not specify "minVersion" property (version 1.20.1, Arclight)

### ISSUE THREAD

**Issue by GabziDev** [AzureDoom/AzureLib#75]
**Minecraft Info:**
Minecraft Version: 1.20.1
Modloader version: Arclight 1.20.1
Mod version: azurelib-neo-1.20.1-2.0.37

I'm encountering an error when starting my Minecraft 1.20.1 server using Arclight with AzureLib. Here are the error details:
```bash
[21:52:29 ERROR] [mixin]: Mixin config azurelib.mixins.json does not specify "minVersion" property
[21:52:29 ERROR] [mixin]: Mixin config azurelib.forge.mixins.json does not specify "minVersion" property
```
It seems that the azurelib.mixins.json and azurelib.forge.mixins.json configuration files are missing the "minVersion" property, causing these errors in the server logs.

![image](https://github.com/user-attachments/assets/40ac69b5-6981-4752-be1a-208eeea7fd00)

**Comment by AzureDoom** [comment]
That isn't an error that causes any issues and can be ignored safely.

**Comment by GabziDev** [comment]
Ok ty
