### ISSUE TITLE
[BUG] Fabric will not notify about CommonNetwork dependency

### ISSUE THREAD

**Issue by ender1324** [AzureDoom/AzureLib#79]
***ALL INFO MUST BE FILLED IN OR THE ISSUE WILL BE CLOSED AS INVALID***

**Minecraft Info:**
Minecraft Version: 1.21.1
Modloader version: 0.16.9
Mod version: 2.3.27

**Describe the bug**
If you install the mod, it will crash if you dont have the common network library and fabric will not notify you about the dependency

**To Reproduce**
1. Install AzureLib
2. Try to launch the game
3. Crash with java.lang.ClassNotFoundException: commonnetwork.networking.data.PacketContext

**Screenshots**
None

**Comment by AzureDoom** [comment]
This mod doesn't use Common Network at all wrong mod
