### ISSUE TITLE
Shader issue again

### ISSUE THREAD

**Issue by FakeACat** [AzureDoom/AzureLib#8]
Shaders that add shadows to mobs cause all mobs of the same type to play the same animations at the same time, for example either every single one of them is playing the walking animation or none of them are, regardless of whether the mob is actually walking. 
A weird thing I noticed is they switch to the correct animation when the game is paused.

Tested on Fabric 1.20.1 with From Another World (my own mod) and Gigeresque.

**Comment by AzureDoom** [comment]
Closing as fixed in latest release.
